import { Capital, Alert, EssentialService } from '@/types';

export const capitals: Capital[] = [
  {
    id: 'financial',
    name: 'Financial',
    score: 68,
    status: 'amber',
    trend: 'stable',
    kris: [
      {
        name: 'Cash Flow Forecast',
        value: '£12.3M surplus',
        trend: 'stable',
        commentary: 'Within planned parameters for Q4',
        dataSource: 'Finance System',
        sourceType: 'standard',
        lastUpdated: new Date('2025-01-15'),
      },
      {
        name: 'Cost Improvement Programme',
        value: '78% achieved',
        trend: 'improving',
        commentary: 'On track to meet annual target',
        dataSource: 'CIP Tracker',
        sourceType: 'standard',
        lastUpdated: new Date('2025-01-14'),
      },
    ],
  },
  {
    id: 'operational',
    name: 'Operational',
    score: 72,
    status: 'green',
    trend: 'improving',
    kris: [
      {
        name: 'A&E 4-Hour Target',
        value: '76.2%',
        trend: 'declining',
        commentary: 'Winter pressures impacting performance',
        dataSource: 'NHS England',
        sourceType: 'public',
        lastUpdated: new Date('2025-01-15'),
      },
      {
        name: 'Bed Occupancy',
        value: '94.5%',
        trend: 'stable',
        commentary: 'Above 92% threshold',
        dataSource: 'Operational Dashboard',
        sourceType: 'standard',
        lastUpdated: new Date('2025-01-15'),
      },
    ],
  },
  {
    id: 'human',
    name: 'Human',
    score: 54,
    status: 'red',
    trend: 'declining',
    kris: [
      {
        name: 'Nurse Vacancy Rate',
        value: '12.4%',
        trend: 'declining',
        commentary: 'Above 10% threshold, active recruitment',
        dataSource: 'HR System',
        sourceType: 'standard',
        lastUpdated: new Date('2025-01-12'),
      },
      {
        name: 'Staff Sickness Rate',
        value: '5.8%',
        trend: 'stable',
        commentary: 'Seasonal increase as expected',
        dataSource: 'HR System',
        sourceType: 'standard',
        lastUpdated: new Date('2025-01-14'),
      },
    ],
  },
  {
    id: 'reputational',
    name: 'Reputational',
    score: 81,
    status: 'green',
    trend: 'improving',
    kris: [
      {
        name: 'Patient Satisfaction',
        value: '87%',
        trend: 'improving',
        commentary: 'Above regional average',
        dataSource: 'Friends & Family Test',
        sourceType: 'public',
        lastUpdated: new Date('2025-01-10'),
      },
      {
        name: 'CQC Rating',
        value: 'Good',
        trend: 'stable',
        commentary: 'Maintained Good rating',
        dataSource: 'CQC',
        sourceType: 'cqc',
        lastUpdated: new Date('2024-11-01'),
      },
    ],
  },
  {
    id: 'environmental',
    name: 'Environmental',
    score: 45,
    status: 'red',
    trend: 'declining',
    kris: [
      {
        name: 'Carbon Emissions',
        value: '-8% YoY',
        trend: 'improving',
        commentary: 'On track for Net Zero 2040',
        dataSource: 'Sustainability Report',
        sourceType: 'standard',
        lastUpdated: new Date('2025-01-01'),
      },
      {
        name: 'Estate Condition',
        value: 'C Rating',
        trend: 'declining',
        commentary: 'Capital programme delayed',
        dataSource: 'ERIC Returns',
        sourceType: 'public',
        lastUpdated: new Date('2024-12-15'),
      },
    ],
  },
];

export const alerts: Alert[] = [
  {
    id: 'alert-1',
    severity: 'red',
    title: 'Critical Staffing Shortage - ICU',
    description: 'ICU nurse staffing at 68% of required levels. Escalation procedures activated.',
    timestamp: new Date('2024-01-15T08:30:00'),
    relatedCapital: 'Human',
    actionUrl: '/workforce/escalation',
  },
  {
    id: 'alert-2',
    severity: 'amber',
    title: 'A&E Performance Below Threshold',
    description: '4-hour wait time at 76.2% against 95% target. Winter pressure protocols active.',
    timestamp: new Date('2024-01-15T07:00:00'),
    relatedCapital: 'Operational',
    actionUrl: '/operations/ae-dashboard',
  },
  {
    id: 'alert-3',
    severity: 'amber',
    title: 'Agency Spend Exceeding Budget',
    description: 'Month-to-date agency spend 15% above plan. Review meeting scheduled.',
    timestamp: new Date('2024-01-14T16:00:00'),
    relatedCapital: 'Financial',
    actionUrl: '/finance/agency-tracker',
  },
  {
    id: 'alert-4',
    severity: 'green',
    title: 'CQC Preparation Complete',
    description: 'All evidence packs submitted and ready for inspection visit.',
    timestamp: new Date('2024-01-14T12:00:00'),
    relatedCapital: 'Reputational',
    actionUrl: '/quality/cqc-tracker',
  },
];

export const essentialServices: EssentialService[] = [
  {
    id: 'es-1',
    name: 'Emergency Department',
    status: 'degraded',
    reason: 'High patient volume, extended wait times',
    lastUpdated: new Date('2024-01-15T09:00:00'),
    impactTolerance: '4 hours',
    criticalPathways: ['Trauma', 'Cardiac', 'Stroke'],
  },
  {
    id: 'es-2',
    name: 'Critical Care',
    status: 'at-risk',
    reason: 'Staffing below minimum safe levels',
    lastUpdated: new Date('2024-01-15T08:30:00'),
    impactTolerance: '2 hours',
    criticalPathways: ['Post-surgical', 'Trauma', 'Respiratory'],
  },
  {
    id: 'es-3',
    name: 'Maternity Services',
    status: 'operational',
    reason: 'All services running normally',
    lastUpdated: new Date('2024-01-15T09:00:00'),
    impactTolerance: '1 hour',
    criticalPathways: ['Labour', 'Neonatal', 'Postnatal'],
  },
  {
    id: 'es-4',
    name: 'Pharmacy',
    status: 'operational',
    reason: 'Stock levels adequate, dispensing on target',
    lastUpdated: new Date('2024-01-15T08:00:00'),
    impactTolerance: '4 hours',
    criticalPathways: ['Chemotherapy', 'Controlled Drugs', 'Antibiotics'],
  },
  {
    id: 'es-5',
    name: 'Diagnostic Imaging',
    status: 'degraded',
    reason: 'MRI scanner maintenance, reduced capacity',
    lastUpdated: new Date('2024-01-15T07:30:00'),
    impactTolerance: '24 hours',
    criticalPathways: ['CT', 'MRI', 'X-Ray', 'Ultrasound'],
  },
];
