import { Capital, Alert, EssentialService } from '@/types';

export const capitals: Capital[] = [
  {
    id: 'financial',
    name: 'Financial',
    score: 68,
    status: 'amber',
    trend: 'stable',
    kris: [
      {
        name: 'Cash Reserves',
        value: '£12.3M',
        trend: 'stable',
        commentary: 'Target: £15M+ | Currently 82% of target',
        dataSource: 'Finance System',
        sourceType: 'standard',
        lastUpdated: new Date('2025-01-15'),
      },
      {
        name: 'Cost Improvement Programme',
        value: '78% achieved',
        trend: 'improving',
        commentary: 'Target: 95% | On track to meet annual target',
        dataSource: 'CIP Tracker',
        sourceType: 'standard',
        lastUpdated: new Date('2025-01-14'),
      },
    ],
  },
  {
    id: 'operational',
    name: 'Operational',
    score: 72,
    status: 'green',
    trend: 'improving',
    kris: [
      {
        name: 'A&E 4-Hour Target',
        value: '76.2%',
        trend: 'declining',
        commentary: 'Target: 95% | NHS average: 74.1%',
        dataSource: 'NHS England',
        sourceType: 'public',
        lastUpdated: new Date('2025-01-15'),
      },
      {
        name: 'Bed Occupancy',
        value: '87%',
        trend: 'stable',
        commentary: 'Target: <92% | NHS average: 89%',
        dataSource: 'Operational Dashboard',
        sourceType: 'standard',
        lastUpdated: new Date('2025-01-15'),
      },
    ],
  },
  {
    id: 'human',
    name: 'Human',
    score: 54,
    status: 'red',
    trend: 'declining',
    kris: [
      {
        name: 'Nurse Vacancy Rate',
        value: '12.4%',
        trend: 'declining',
        commentary: 'Target: <10% | NHS average: 9.8%',
        dataSource: 'HR System',
        sourceType: 'standard',
        lastUpdated: new Date('2025-01-12'),
      },
      {
        name: 'Staff Sickness Rate',
        value: '5.8%',
        trend: 'stable',
        commentary: 'Target: <4.5% | NHS average: 5.2%',
        dataSource: 'HR System',
        sourceType: 'standard',
        lastUpdated: new Date('2025-01-14'),
      },
    ],
  },
  {
    id: 'reputational',
    name: 'Reputational',
    score: 81,
    status: 'green',
    trend: 'improving',
    kris: [
      {
        name: 'Patient Satisfaction',
        value: '87%',
        trend: 'improving',
        commentary: 'Target: >85% | NHS average: 82%',
        dataSource: 'Friends & Family Test',
        sourceType: 'public',
        lastUpdated: new Date('2025-01-10'),
      },
      {
        name: 'CQC Rating',
        value: 'Good',
        trend: 'stable',
        commentary: 'Last inspection: Jul 2023 | Next due: Q2 2025',
        dataSource: 'CQC',
        sourceType: 'cqc',
        lastUpdated: new Date('2024-11-01'),
      },
    ],
  },
  {
    id: 'environmental',
    name: 'Environmental',
    score: 45,
    status: 'red',
    trend: 'declining',
    kris: [
      {
        name: 'Carbon Emissions',
        value: '-8% YoY',
        trend: 'improving',
        commentary: 'Target: -10% YoY | NHS avg: -4% YoY',
        dataSource: 'Sustainability Report',
        sourceType: 'standard',
        lastUpdated: new Date('2025-01-01'),
      },
      {
        name: 'Estate Condition',
        value: 'C Rating',
        trend: 'declining',
        commentary: 'Target: B Rating | NHS avg: C Rating',
        dataSource: 'ERIC Returns',
        sourceType: 'public',
        lastUpdated: new Date('2024-12-15'),
      },
    ],
  },
];

export const alerts: Alert[] = [
  {
    id: 'alert-1',
    severity: 'amber',
    title: 'Critical care beds at 87% occupancy',
    description: 'Monitoring capacity. Normal range 85-92%.',
    timestamp: new Date('2025-01-24T09:15:00'),
    relatedCapital: 'Operational',
    actionUrl: '/operations/bed-management',
  },
  {
    id: 'alert-2',
    severity: 'red',
    title: 'Agency nurse costs 23% above budget',
    description: 'Unsustainable spend driven by permanent staff vacancies. Urgent workforce planning required.',
    timestamp: new Date('2025-01-24T08:30:00'),
    relatedCapital: 'Financial',
    actionUrl: '/finance/agency-tracker',
  },
  {
    id: 'alert-3',
    severity: 'amber',
    title: 'Cyber threat level elevated',
    description: 'Phishing attempts targeting staff emails detected. IT security conducting awareness campaign.',
    timestamp: new Date('2025-01-24T07:45:00'),
    relatedCapital: 'Operational',
    actionUrl: '/it/security-dashboard',
  },
  {
    id: 'alert-4',
    severity: 'amber',
    title: 'Elective surgery cancellations increasing',
    description: '12% cancellation rate this week due to bed capacity constraints. Risk to waiting times target.',
    timestamp: new Date('2025-01-23T16:20:00'),
    relatedCapital: 'Reputational',
    actionUrl: '/operations/elective-tracker',
  },
];

export const essentialServices: EssentialService[] = [
  {
    id: 'es-1',
    name: 'Emergency Care',
    status: 'operational',
    reason: 'All pathways operating within normal parameters',
    lastUpdated: new Date('2025-01-24T10:00:00'),
    impactTolerance: '4 hours',
    criticalPathways: ['Trauma', 'Cardiac', 'Stroke'],
  },
  {
    id: 'es-2',
    name: 'Elective Surgery',
    status: 'degraded',
    reason: 'Reduced capacity due to bed availability constraints',
    lastUpdated: new Date('2025-01-24T09:30:00'),
    impactTolerance: '24 hours',
    criticalPathways: ['Orthopaedic', 'General', 'Cardiac'],
  },
  {
    id: 'es-3',
    name: 'Mental Health Crisis',
    status: 'at-risk',
    reason: 'Section 136 suite at capacity, police custody being used',
    lastUpdated: new Date('2025-01-24T08:45:00'),
    impactTolerance: '2 hours',
    criticalPathways: ['Section 136', 'Crisis Team', 'CAMHS'],
  },
  {
    id: 'es-4',
    name: 'Maternity Services',
    status: 'operational',
    reason: 'All pathways functioning, staffing levels adequate',
    lastUpdated: new Date('2025-01-24T10:15:00'),
    impactTolerance: '1 hour',
    criticalPathways: ['Labour', 'Neonatal', 'Postnatal'],
  },
  {
    id: 'es-5',
    name: 'Diagnostics',
    status: 'degraded',
    reason: 'CT scanner downtime, patients being referred to neighbouring trust',
    lastUpdated: new Date('2025-01-24T07:00:00'),
    impactTolerance: '12 hours',
    criticalPathways: ['CT', 'MRI', 'X-Ray', 'Ultrasound'],
  },
];
